### ISSUE TITLE
Error when searching a string of <= 2 characters

### ISSUE THREAD

**Issue by sleeyax** [sleeyax/paulo#7]
Searching for `a` or `tv` results in the following error:
```
ExpectedConstraintError > s.number.lessThanOrEqual
  Invalid number value

  Expected: expected <= 25

  Received:
  | 26

    at Object.run (/app/node_modules/@sapphire/shapeshift/dist/index.js:757:72)
    at /app/node_modules/@sapphire/shapeshift/dist/index.js:201:66
    at Array.reduce (<anonymous>)
    at NumberValidator.parse (/app/node_modules/@sapphire/shapeshift/dist/index.js:201:29)
    at validateFieldLength (/app/node_modules/@discordjs/builders/dist/index.js:127:24)
    at EmbedBuilder.addFields (/app/node_modules/@discordjs/builders/dist/index.js:207:5)
    at /app/dist/commands/search.js:38:23
    at Generator.next (<anonymous>)
    at fulfilled (/app/dist/commands/search.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

It looks like searching for anything <=  2 characters throws this error. This seems to be an underlying issue with discord.js itself...

**Comment by sleeyax** [comment]
Actually, never mind. This is caused because the bot somehow goes over the max. allowed of embedded fields in its reply.
